#!/bin/bash

THISDIR=`dirname $0`
export LD_LIBRARY_PATH=$THISDIR:$LD_LIBRARY_PATH

mono --profile=default:stat $THISDIR/DifferenceClouds.exe "$@"
#mono $THISDIR/Forge.exe "$@"
#mono --debug $THISDIR/Forge.exe "$@"
