#!/bin/bash

THISDIR=`dirname $0`
export LD_LIBRARY_PATH=$THISDIR:$LD_LIBRARY_PATH

# Fixme: find out were ironpython is installed!

export MONO_PATH=/usr/lib/ironpython/:$MONO_PATH

export PLUGINDIR=`gimptool-2.0 --gimpplugindir`"/plug-ins"

mono $THISDIR/PythonSample.exe "$@"
